Online public notice - show 'disclaimer' after each notice
bcgov/nr-fom pull request #232
Opened 2022-08-20 18:54 UTC by DerekRoberts

For the public site list of public notices, show the 'disclaimer' text after each notice and reword to "This FOM...".

Disclaimer text currently is: "These FOM can be relied upon by the FOM holder for the purpose of a cutting permit or road permit application, or the issuance of a Timber Sales License until the date three years after commencement of the public review and commenting period."

2022-08-20 19:08 UTC, DerekRoberts commented
@basilv No way this task is so small, right?!?  I must've misunderstood something...

2022-08-22 14:12 UTC, basilv commented
I looked at https://fom-232.apps.silver.devops.gov.bc.ca/public/projects#publicNotices but don't see any change.

2022-08-22 14:12 UTC, basilv requested changes, later dismissed
You changed the wording of the disclaimer, but didn't change its location - it needs to appear at the end of each notice, not at the end of the entire page.

2022-08-22 17:06 UTC, basilv commented
Better, but still need to remove the disclaimer at the bottom of the page.

2022-08-22 17:23 UTC, DerekRoberts commented
@basilv Done!

2022-08-22 17:29 UTC, basilv approved these changes

2022-08-22 18:03 UTC, merged